import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Prisma — it ships its own @ts-nocheck and eslint-disable,
    // and regenerating would discard anything we changed anyway.
    "lib/generated/**",
    // Scratch files owned by tooling, not part of the app.
    ".remember/**",
  ]),
]);

export default eslintConfig;
